architecture: replication
auth:
  rootPassword: root
  database: db
  username: my-user
  password: my-pass

secondary:
  # 1 primary and 2 secondary replicas
  replicaCount: 2
  persistence:
    storageClass: standard
